### ISSUE TITLE
notwork, trying to send base64 data but getting error

### ISSUE THREAD

**Issue by breign** [unwriter/BitcoinMediaUpload#1]
Keep getting error:
 `{"error":"64: scriptpubkey. Code:-26"}
`
```
code is:
      const tx = {
        data: ["", String(imgb64)],
        pay: { 
          key: privateKey
        }
      }
      datapay.send(tx, function(err, res) {
        if (err) {
```
...
What am I doing wrong?

**Comment by opReturn0** [comment]
i have exact the same issue, troubleshooting it as we speak

**Comment by breign** [comment]
if I build TX and send it via https://whatsonchain.com/broadcast it worx

**Comment by opReturn0** [comment]
ok, good to know. It probably is an issue with datapay and the service/node it communicates with.

**Comment by breign** [comment]
also, I noted that it prepends base64 with some extra bytes, can I override that?
[tx example of an image](https://whatsonchain.com/tx/ae203daa9acddb73fa4a3907799594edc03c71f3358ddf255fe33611e8c73511)

P.S. I'm node noob.

**Comment by opReturn0** [comment]
what did you do to post the raw tx? the base64 is not accepted by whatsonchain

**Comment by torusJKL** [comment]
I think the raw tx needs to be in hex.

**Comment by opReturn0** [comment]
OK i got it to send a tx - but as with @breign some data is prepended which breaks it

**Comment by breign** [comment]
> what did you do to post the raw tx? the base64 is not accepted by whatsonchain

image inside tx was encoded base64, not tx. but something prepended that image base64 data.

**Comment by opReturn0** [comment]
yes "Mg" is prepended, i tried some tricks but no luck so far

**Comment by opReturn0** [comment]
The prepending issue might be related to WoC - I informed the operator. The op_return looks good in electrumsv

**Comment by breign** [comment]
any other compatible xplorers for datapay or just https://bchsvexplorer.com ?

**Comment by breign** [comment]
I closed this issue because I figured it out.
